### ISSUE TITLE
Add YYZ support

### ISSUE THREAD

**Issue by expected-ingot** [KuromeSan/GayMaker#11]
Trying to port my game Clicki but it's YYZ not YYP

**Comment by PSVita-Dev** [comment]
This tool loads .project.gmx and not .yyp nor YYZ. It is only supporting 1.4 versions of GM:S. Why? Cause yoyo games didnt Make a runner for 2.+ ."buissnes reasons"

**Comment by KuromeSan** [comment]
It is technically possible to run alot of GMS2 games on vita using the 1.4.9999 runner. But I don't want to support that..

**Comment by rhebok-git** [comment]
> It is technically possible to run alot of GMS2 games on vita using the 1.4.9999 runner. But I don't want to support that..

No plans on GMS2 to Vita then ? That's my wet dream though :p

**Comment by KuromeSan** [comment]
its not really GMS2 on vita its just using the GMS2 editor to make GMS1.4.9999 games.

**Comment by expected-ingot** [comment]
@pkostic-dev https://wololo.net/2022/04/21/ps-vita-yoyoloader-updates-99-games-playable-and-rising/ I found this
