### ISSUE TITLE
Compiling shaders without YYC makes compiler crash when loading rooms

### ISSUE THREAD

**Issue by infamoussabre** [KuromeSan/GayMaker#12]
### Compiling a game that uses shaders without enabling YYC makes 1.7.6 compiler crash when loading rooms. 

_The previous issue #8 regarding this was closed because the poster decided to use an old version that did not have this issue. This is not a reason to close the issue since it is still present in the current version, therefore here it is again._

`Reading project file....System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at GMAssetCompiler.GMShader.ExecuteCMDWithResult(String exe, String cmdLine, String& result)
   at GMAssetCompiler.GMShader.CompileCGfromGLSLES()
   at GMAssetCompiler.GMShader.PrepareShader()
   at GMAssetCompiler.GMShader..ctor( _a, String _ShaderFileName, String _type)
   at ...ctor(XmlDocument Â—, String )`

**Comment by KuromeSan** [comment]
You found the bug?! I wasn't really paying attention to issues for last forever because I assumed it was a GMAC issue so possibly bug at yoyos side but I now see it was just me doing it wrong .. nice find

**Comment by MDashK** [comment]
> You found the bug?! I wasn't really paying attention to issues for last forever because I assumed it was a GMAC issue so possibly bug at yoyos side but I now see it was just me doing it wrong .. nice find

Yeah, I took the liberty of forking it and compiling both the Vita and PS4 version with the big fixed. =)

**Comment by KuromeSan** [comment]
fixed
