### ISSUE TITLE
Could not find any rooms

### ISSUE THREAD

**Issue by EGAMatsu** [KuromeSan/GayMaker#13]
![image](https://user-images.githubusercontent.com/58616438/127527238-d6f4ad09-4e99-47ba-8ae6-6c2fa7c264c1.png)
![image](https://user-images.githubusercontent.com/58616438/127527256-8d07e344-df2d-4001-add6-983fb66504b7.png)

**Comment by KuromeSan** [comment]
You are using GM 1.4.9999 to build a project created with 1.4.1567 ..

**Comment by KuromeSan** [comment]
apparently this is related to #12 , which i fixed. so this should also be fixed.
