### ISSUE TITLE
GMS 2 .yyp Projects

### ISSUE THREAD

**Issue by MrWiliGuonKa** [KuromeSan/GayMaker#6]
Are you going to make a version where you can export the GMS2 projects into the PS Vita??  Thanks !!

**Comment by KuromeSan** [comment]
YoYo games offers no GMS2 support, although its true you can hack together GMS1.4.9999's runner to play some GMS2 games. i dont wanna try support that sort of hacked together stuff in GayMaker, 

Chovy-GM Is bad enough xD

**Comment by m1s3ry** [comment]
You can use ReVitalizer from YellowAfterlife to convert GMS 2 projects back to GMS 1.4
