### ISSUE TITLE
[Error] Compiling shaders with psp2cgc.exe makes compiler crash when loading rooms

### ISSUE THREAD

**Issue by m1s3ry** [KuromeSan/GayMaker#8]
Edit: I now know what is causing the problem. Even though I loaded psp2cgc.exe properly when I'm prompted in GayMaker, it makes the compiler return a "no room founds" error, telling that the project may be corrupted. 
This can be because of my psp2cgc.exe file but I download 3 different ones from the internet and they all have the same checksum, so I don't think mine is corrupted or anything like that.

-------------------------------------------------------------------------

The project I'm trying to convert has a lot of rooms, and each time I try to compile it with GayMaker it says there are no rooms in the project, suggesting that it could be caused by project corruption.

Thing is, if I use GMS I can compile and play the project without any problem. What could be causing this?

**Comment by m1s3ry** [comment]
I must say that for other projects it has worked fine, but for this specific project it keeps failing. I did things like exporting every resource, creating a new project, importing everything and it still fails. 
It's the only project that has this specific error
`Reading project file....System.ComponentModel.Win32Exception: El sistema no puede encontrar el archivo especificado
   en System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   en GMAssetCompiler.GMShader.ExecuteCMDWithResult(String exe, String cmdLine, String& result)
   en GMAssetCompiler.GMShader.CompileCGfromGLSLES()
   en GMAssetCompiler.GMShader.PrepareShader()
   en GMAssetCompiler.GMShader..ctor( _a, String _ShaderFileName, String _type)
   en ...ctor(XmlDocument Â—, String )
Compile Constants...finished.`

**Comment by KuromeSan** [comment]
no ' System.ComponentMode.Win32Exception' is the error itself 

https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.win32exception?view=netcore-3.1

according to these docs its an exception that can be thrown by another external application (i guess psp2cgc ?) and is not part of the main executable (so say, GMAssetCompiler.exe)

**Comment by m1s3ry** [comment]
@KuromeSan I wouldn't know. It seems that is the problem, because I can compile projects without shaders without any problem.
psp2cgc.exe is located in GayMaker 1.7.6/psvitasdk/host_tools/bin. It was automatically put in there when I was prompted to select the file the first time I tried to compile a project with shaders.

**Comment by KuromeSan** [comment]
It also sets an environment variable "%SCE_PSP2_SDK_DIR% whenever it runs the gmassetcompiler. So it thinks there's an SDK installation there.

**Comment by rhebok-git** [comment]
Hi I'm having the same issue. This is the line argument.

> Can you post the command line arguments it's passing to gmassetcompiler?

```-- GMASSETCOMPILER BEGIN --
GMAssetCompiler.exe /c /m=psvita /config="Default" /tgt=2147483648 /obob=True /obpp=False /obru=True /obes=False /i=3 /cvm /tp=2048 /mv=1 /iv=0 /rv=0 /bv=9999 /sh=true / psvitasdk="C:\Users\Rhebok\Documents\GameMaker\Projects\VitaGame.gmx\GayMaker.1.7.6\psvitasdk" /gn="GM:S" /o="C:\Users\Rhebok\Documents\GameMaker\Projects\VitaGame.gmx\_temp\games" "C:\Users\Rhebok\Documents\GameMaker\Projects\VitaGame.gmx\VitaGame.project.gmx"
Reading project file....System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at GMAssetCompiler.GMShader.ExecuteCMDWithResult(String exe, String cmdLine, String& result)
   at GMAssetCompiler.GMShader.CompileCGfromGLSLES()
   at GMAssetCompiler.GMShader.PrepareShader()
   at GMAssetCompiler.GMShader..ctor( _a, String _ShaderFileName, String _type)
   at ...ctor(XmlDocument Â—, String )```

**Comment by KuromeSan** [comment]
very weird, only weird thing i see is that its all in the project folder for the game.. which might cause issues

**Comment by m1s3ry** [comment]
Close issue: This only happens with gm 1.7.5 and 1.7.6 when compiling shaders without YYC, anything starting from 1.7.4 and below works well. 1.7.5 and 1.7.6 also works well with shaders as long as YYC is used.

**Comment by rhebok-git** [comment]
> Close issue: This only happens with gm 1.7.5 and 1.7.6 when compiling shaders without YYC, anything starting from 1.7.4 and below works well. 1.7.5 and 1.7.6 also works well with shaders as long as YYC is used.

Who are you, who are so wise in the ways of science ?
I tested with the 1.7.4 version and it works great 👌
