### ISSUE TITLE
png color change

### ISSUE THREAD

**Issue by legomeaker101** [KuromeSan/GayMaker#9]
I have been working on an improved port of spelunky classic for vita but when i put the png's i made for the game into gaymaker it makes everything look a more blue so things look really odd.

I have manually changed the png's with vitashel which made them look much better so I know it is something gaymaker is doing.

**Comment by KuromeSan** [comment]
Please use PNGs with 8 bits per pixel indexed color, this is the only ones the PSVita officially supports. GayMaker will attempt to convert pngs not in this format to this format at compile time..
